### ISSUE TITLE
Is Miranda-TLS hardware open sourced?

### ISSUE THREAD

**Issue by haoyihan** [Rotoslider/Miranda-TLS#1]
Hello Rotoslider,
    We wants to build a realtime TLS system , and I find Miranda-TLS is the most compact solution. So I want to ask if this project is hardware-open-sourced.

**Comment by Rotoslider** [comment]
There is not much too it. A lidar of your choice and mini computer of your choice and your good to go. I used a Miranda motor by Overview and a Jetson nano. You could use a pie or some other computer I have not put up any cad models for it as of this time. I may in the future

**Comment by haoyihan** [comment]
Got it. Thanks~
